name: example
description: Example using Flutter Duration Picker

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_duration_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true